#!/bin/bash
#!/usr/bin/env bash

BUILD_DIR=cmake-build-debug
MAKEFILES="Unix Makefiles"
MAKE=make
MAKE_FLAGS=-j5

set -o errexit
trap 'echo "Aborting due to errexit on line $LINENO. Exit code: $?" >&2' ERR
set -o errtrace
set -o pipefail
DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"
_ME=$(basename "${0}")

_print_help() {
  cat <<HEREDOC
                 __               .__
__  _  _______ _/  |_  ___________|  |   ____   ____ ______
\\ \\/ \\/ /\\__  \\\\   __\\/ __ \\_  __ \\  |  /  _ \\ /  _ \\\\____ \\
 \\     /  / __ \\|  | \\  ___/|  | \\/  |_(  <_> |  <_> )  |_> >
  \\/\\_/  (____  /__|  \\___  >__|  |____/\\____/ \\____/|   __/
              \\/          \\/                         |__|

The Embedded C++ code base builder

HEREDOC
}

_build(){
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR
    echo "Running CMake"
    cmake -G "$MAKEFILES" ..
    echo "Running Make"
    $MAKE $MAKE_FLAGS
    echo "Project Built"
    cd ..
}

_clean(){
    if [ -d "$BUILD_DIR" ] ; then
        cd $BUILD_DIR
        make clean
    fi
}

_make() {
    cd $BUILD_DIR
    $MAKE
}

_reset() {
    rm -rf $BUILD_DIR
}

_run() {
    ./$BUILD_DIR/minotaur-cpp
}

_test() {
    _build
    _run
}

_simple() {
    root_dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
    root_dir_name=$(basename "$root_dir")
    cd "$root_dir"

    if [ "$1" == 'build' ] ; then
        echo "Building project"
        _build
    elif [ "$1" == 'clean' ] ; then
        echo "Cleaning project"
        _clean
    elif [ "$1" == 'reset' ] ; then
        echo "Resetting project"
        _reset
    elif [ "$1" == 'run' ] ; then
        _run
    elif [ "$1" == 'test' ] ; then
        _test
    elif [ "$1" == 'make' ] ; then
        _make
    else
        _print_help
    fi
}

_main() {
  # Avoid complex option parsing when only one program option is expected.
  if [[ "${1:-}" =~ ^-h|--help$  ]] || [ $# -lt "1" ]
  then
    _print_help
  else
    _simple "$@"
  fi
}

_main "$@"
