set(GOTURN_PROTOTXT ${CMAKE_CURRENT_SOURCE_DIR}/goturn.prototxt)
set(GOTURN_CAFFEMODEL ${CMAKE_CURRENT_SOURCE_DIR}/goturn.caffemodel)
log("Looking for GOTURN files under ${CMAKE_CURRENT_SOURCE_DIR}")
option(NO_GOTURN "Build minotaur without GOTURN" OFF)
if (EXISTS ${GOTURN_PROTOTXT} AND EXISTS ${GOTURN_CAFFEMODEL} AND NOT NO_GOTURN)
    log("GOTURN files found")
    set(GOTURN_FILES_FOUND TRUE)
    configure_file(${GOTURN_PROTOTXT} goturn.prototxt COPYONLY)
    configure_file(${GOTURN_CAFFEMODEL} goturn.caffemodel COPYONLY)
else ()
    log("GOTURN not found")
    set(GOTURN_FILES_FOUND FALSE)
endif ()
